### PR TITLE
Footer

### PR DESCRIPTION
**Pull request by Jaro11**
**Fixed some bugs:**
- movie results in the mobile view - removed the padding so that it displays saved time within the container - 
- custom results - changed the font size and padding to have answer displayed properly within container
image
- history - custom results - fixed font size so that it is properly displayed

**Footer:**
- Added collapse function from bootstrap to footer
- Still can not fix the footer to be always down in login page. I guess we would need flexbox on the body as well.

   **- Still to do in Footer**
   - still need to change the colors and have the links functioning in footer
   - dropdown button is not well positioned in mobile view
   - direction of the footer opening, it goes down and I would like to have it moving upwards

### CODE REVIEW

**Comment by ronanoboyle** [comment]
@Jaro11 Sorry I meant #34 in my comment

**Comment by Jaro11** [comment]
I can see there are conflicts. @ronanoboyle I can not find your comment somehow. Is it in your commit?

**Comment by ronanoboyle** [comment]
@Jaro11 For me it's just in this feed -> 
Screenshot 2023-03-26 at 20 55 42

**Comment by Jaro11** [comment]
I can do it. I did pull origin master, but then I continued on old branch, where I did not pull origin master again I guess. I should have had created new branch, I guess.

**Pull request merged**
